server:
  port: 3000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/i_am_done
    username: postgres
    password: 2023
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
